### ISSUE TITLE
OSX : Aenea server setup : test-client.py does not work for 192.168.x.x but works for loopback (127.0.0.1)

### ISSUE THREAD

**Issue by shivshankark** [dictation-toolbox/aenea#113]
Hi All,

First of all, thanks for setting up this project. I am really looking forward to use this to get rid of my RSI.
I have followed all the steps in server setup. When I try to test it out, I could connect server with loopback address in config.py but it does not work when using 192.168.x.x IP. I tried with both 'Host only adapter' settings and 'NAT', but no luck. The server starts, but client says 'Operation timed out'.

Please help.

Here are logs.
**Terminal 1 - Server**
 ```bash
:: python server_osx.py
started on host = 192.168.1.104 port = 8240
```
**Terminal 2 - Client**
 ```bash
::python test-client.py
HOST=
192.168.1.104
PORT=
8240
Traceback (most recent call last):
  File "test-client.py", line 129, in <module>
    main()
  File "test-client.py", line 123, in main
    all_tests(communication.server)
  File "test-client.py", line 107, in all_tests
    test_key_press(distobj)
  File "test-client.py", line 44, in test_key_press
    distobj.key_press(key='a')
  File "/Library/Python/2.7/site-packages/jsonrpclib/jsonrpc.py", line 290, in __call__
    return self.__send(self.__name, kwargs)
  File "/Library/Python/2.7/site-packages/jsonrpclib/jsonrpc.py", line 237, in _request
    response = self._run_request(request)
  File "/Library/Python/2.7/site-packages/jsonrpclib/jsonrpc.py", line 255, in _run_request
    verbose=self.__verbose
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xmlrpclib.py", line 1264, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xmlrpclib.py", line 1292, in single_request
    self.send_content(h, request_body)
  File "/Library/Python/2.7/site-packages/jsonrpclib/jsonrpc.py", line 126, in send_content
    connection.endheaders()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 969, in endheaders
    self._send_output(message_body)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 829, in _send_output
    self.send(msg)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 791, in send
    self.connect()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 772, in connect
    self.timeout, self.source_address)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 571, in create_connection
    raise err
socket.error: [Errno 60] Operation timed out
```

**Comment by mzizzi** [comment]
After starting the server process in "terminal 1" can you connect to it at all?

e.g.
**Server - Terminal 1**
```
python server_osx.py
started on host = 192.168.1.104 port = 8240
...
```

**Shell - Terminal 2**
```
telnet 192.168.1.104 8240
```

Setup for the project is a very involved process.  Fortunately you only have to do it once.

**Comment by shivshankark** [comment]
Nope, I am not able to telnet with 192.168.x.x. I can do it with 127.0.0.1 though. 
I cant even ping the self ip 192.168.x.x. Do you know if there is any setting on Mac to enable ping / telnet to self ip 192.168 ?

**Comment by calmofthestorm** [comment]
I don't know anything about mac specifically, but since it's timing out rather than being refused and even telnet does not work, this sounds like you may have some kind of antivirus or firewall installed. Make sure that port 8240 is open, it sounds like it's not. You could also change the port aenea uses, just make sure to do it in both [test] client and server configs.
