### ISSUE TITLE
 argument of type 'NoneType' is not iterable

### ISSUE THREAD

**Issue by dylan-chong** [dictation-toolbox/aenea#171]
```
 UnimacroDirectory: C:\NatLink\Unimacro
setting shiftkey to: {shift} (language: enx)
start of natlinkstartup
Vocola not active
Aenea client-side modules loaded successfully
Settings:
	HOST: 192.168.56.1
	PORT: 8240
	PLATFORM: proxy
	USE_MULTIPLE_ACTIONS: True
	SCREEN_RESOLUTION: [6400, 1440]
Aenea: Successfully connected to server.
Loading _charwise_vim.py
natlinkmain started from C:\NatLink\NatLink\MacroSystem\core:
  NatLink version: 4.1romeo
  DNS version: 12
  Python version: 27
  Windows Version: 7

----------------------------------------
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\dragonfly\engines\engine_natlink.py", line 225, in begin_callback
    self.grammar.process_begin(executable, title, handle)
  File "C:\Python27\lib\site-packages\dragonfly\grammar\grammar_base.py", line 353, in process_begin
    or self._context.matches(executable, title, handle):
  File "C:\NatLink\NatLink\MacroSystem\aenea\wrappers.py", line 212, in matches
    return context.matches(executable, title, handle)
  File "C:\NatLink\NatLink\MacroSystem\aenea\proxy_contexts.py", line 145, in matches
    return self._reduce_matches(self._check_properties())
  File "C:\NatLink\NatLink\MacroSystem\aenea\proxy_contexts.py", line 116, in _check_properties
    elif key in properties:
TypeError: argument of type 'NoneType' is not iterable
```

For as long as I can remember, I get this exception in the Nat link log after starting up dragon and then trying to dictate. Has anyone seen this before?

**Comment by dylan-chong** [comment]
I haven't seen this bug happen at least since i have upgraded to dragonfly2, i will close this issue for now
