### ISSUE TITLE
"force natlink to reload all grammars" occasionally causes errors

### ISSUE THREAD

**Issue by djr7C4** [dictation-toolbox/aenea#77]
Specifically, sometimes modules used in grammars are set to None after running this command but this does not always happen.  This causes obvious problems when grammars attempt to refer to those modules...

Presumeably, this command sometimes unloads modules it shouldn't (modules imported from grammars are unloaded and then reloaded in the implementation).  It's also possible that it might reload things in the wrong order which could also cause problems (this seems like the most likely cause).

**Comment by djr7C4** [comment]
Is anyone still encountering this issue?  I have not had it happen for some time now so perhaps it was fixed by some other change.

**Comment by Yorgg** [comment]
I am encountering this issue.   I need to restart dragon each time i update the files :(

**Comment by djr7C4** [comment]
I'm sure a pull request would be welcome :-)

**Comment by Haggr** [comment]
I encountered the error as well and made a makeshift fix. I don't think the solution is worth a pull request but I can elaborate on the problem to make it easy to fix later on.

I first encountered the problem when I started to use _multiedit.py. The unload function was causing the problem. Long story short, this grammar deals with the vocabulary grammar to inhibit/uninhibit some vocabularies. It calls on to uninhibit them while unloading. Not sure how that works but the vocabulary grammar is multiedit's wrapper. I don't even know what wrapper means in this case. The problem occurs because the vocabulary grammar is the first to unload. Thus, when multiedit attemps to unload, because the "wrapper" is not loaded, it raises an error. The traceback is at the bottom.

My dumbass solution was to just go to the unloadEverything function in core/natlinkmain.py and hardcode into it that it should unload the grammar named "_vocabulary" the last.

```
Error calling _multiedit.unload
Traceback (most recent call last):
  File "C:\Natlink\Natlink\MacroSystem\core\natlinkmain.py", line 360, in safelyCall
    apply(func, [])
  File "C:\Natlink\Natlink\MacroSystem\_multiedit.py", line 339, in unload
    aenea.vocabulary.uninhibit_global_dynamic_vocabulary('multiedit', MULTIEDIT_TAGS)
  File "C:\Natlink\Natlink\MacroSystem\aenea\vocabulary.py", line 293, in uninhibit_global_dynamic_vocabulary
    uninhibit_global_dynamic_vocabulary(grammar_name, t)
  File "C:\Natlink\Natlink\MacroSystem\aenea\vocabulary.py", line 290, in uninhibit_global_dynamic_vocabulary
    _rebuild_lists('dynamic')
  File "C:\Natlink\Natlink\MacroSystem\aenea\vocabulary.py", line 162, in _rebuild_lists
    _global_list.clear()
  File "C:\Python27\lib\site-packages\dragonfly\grammar\list.py", line 272, in clear
    self._update(); return result
  File "C:\Python27\lib\site-packages\dragonfly\grammar\list.py", line 115, in _update
    self._grammar.update_list(self)
  File "C:\Python27\lib\site-packages\dragonfly\grammar\grammar_base.py", line 337, in update_list
    self._engine.update_list(lst, self)
  File "C:\Python27\lib\site-packages\dragonfly\engines\backend_natlink\engine.py", line 282, in update_list
    wrapper = self._get_grammar_wrapper(grammar)
  File "C:\Python27\lib\site-packages\dragonfly\engines\base\engine.py", line 191, in _get_grammar_wrapper
    raise EngineError("Grammar %s never loaded." % grammar)
EngineError: Grammar Grammar(vocabulary) never loaded.
```
