### ISSUE TITLE
json-rpc ProtocolError

### ISSUE THREAD

**Issue by InfernalLV** [dictation-toolbox/aenea#94]
Hey,​
I'm trying to setup aenea on a Windows 10 machine to use in order to take advantage of the added functionality of aenea and the grammars contributed by the community. 

Currently I'm stuck at the setup aenea itself. If you have a spare moment and you could look at the trace I would be grateful. 

I launch windows server.
`aenea.exe -a 127.0.0.1`
 

```
`C:\NatLink\NatLink\MacroSystem\aenea.json`  
{
    "host": "127.0.0.1",
    "port": 8240,
    "platform": "proxy",
    "use_multiple_actions": false,
    "screen_resolution": [6400, 1440],
    "project_root": "C:\\NatLink\\NatLink\\MacroSystem",
    "restrict_proxy_to_aenea_client": false
}
```

The _hello_world_aenea.py test fails upon attempting to send the RPC request. Trace: 
```
 Vocola not active
Aenea hello world grammar: Loaded.

--- WARNING: Speech Model BestMatch V is used for this User Profile
The performance of many NatLink grammars is not good with this model.
Please choose another User Profile with for example Speech Model BestMatch IV.
See http://unimacro.antenna.nl/installation/speechmodel.html
----
natlinkmain started from C:\NatLink\NatLink\MacroSystem\core:
  NatLink version: 4.1lima
  DNS version: 12
  Python version: 27
  Windows Version: 8

Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\dragonfly\engines\engine_natlink.py", line 248, in results_callback
    r.process_recognition(root)
  File "C:\Python27\lib\site-packages\dragonfly\grammar\rule_mapping.py", line 181, in process_recognition
    self._process_recognition(item_value, extras)
  File "C:\Python27\lib\site-packages\dragonfly\grammar\rule_mapping.py", line 201, in _process_recognition
    value.execute(extras)
  File "C:\Python27\lib\site-packages\dragonfly\actions\action_base.py", line 127, in execute
    if self._execute(data) == False:
  File "C:\NatLink\NatLink\MacroSystem\aenea\wrappers.py", line 201, in _execute
    self._data = ensure_execution_context(data)
  File "C:\NatLink\NatLink\MacroSystem\aenea\wrappers.py", line 111, in ensure_execution_context
    data['_server_info'] = aenea.proxy_contexts._server_info()
  File "C:\NatLink\NatLink\MacroSystem\aenea\proxy_contexts.py", line 82, in _server_info
    _refresh_server()
  File "C:\NatLink\NatLink\MacroSystem\aenea\proxy_contexts.py", line 64, in _refresh_server
    _last_server_info = aenea.communications.server.server_info()
  File "C:\NatLink\NatLink\MacroSystem\aenea\communications.py", line 104, in call
    return self._execute_batch([(meth, a, kw)])
  File "C:\NatLink\NatLink\MacroSystem\aenea\communications.py", line 87, in _execute_batch
    batch[0][0])(*batch[0][1], **batch[0][2])
  File "C:\Python27\lib\site-packages\jsonrpclib\jsonrpc.py", line 276, in __call__
    return self.__send(self.__name, kwargs)
  File "C:\Python27\lib\site-packages\jsonrpclib\jsonrpc.py", line 225, in _request
    check_for_errors(response)
  File "C:\Python27\lib\site-packages\jsonrpclib\jsonrpc.py", line 529, in check_for_errors
    raise ProtocolError((code, message))
jsonrpclib.jsonrpc.ProtocolError: (-32601, u'Method not found: server_info')
```

I have the python libs in the global-sites packages.
```
dragonfly==0.6.5
jsonrpclib==0.1.3
pygame==1.9.1
pyparsing==2.0.3
pywin32==218
PyXML==0.8.4
```

I noticed that if I print the address from Proxy class's _execute_batch it points to u'localhost'. no matter what I pout in the aenea.json . 

If I set the server to 192.168.56.1 it gives the error pasted above.

If the server is set to `localhost` I get the error bellow.
```
Socket error connecting to aenea server. To avoid slowing dictation, we won't try again for 5 seconds.
```

Any help much appreciated.

**Comment by grayjay** [comment]
I just realized that this is a problem with the Windows server.  It only supports the methods key_press, write_text, pause, and get_context from an older version of the client.  Where can I find the current JSON-RPC interface?

**Comment by mzizzi** [comment]
Take a look at the linux x11 server.

https://github.com/dictation-toolbox/aenea/blob/master/server/linux_x11/server_x11.py#L473

**Comment by grayjay** [comment]
Thanks!  It looks like server_info has a static response that would be easy to add to the Windows server: https://github.com/dictation-toolbox/aenea/blob/master/server/linux_x11/server_x11.py#L87 .  The only other method that was added since I wrote the server is notify.  Is notify a required method?

**Comment by mzizzi** [comment]
Notify is just used by the x11 server to print text notifications to the desktop.  It is not a requirement although it may be a useful feature to consider in the future.
